const JWTToken = require("jsonwebtoken");
const sendToken = (user, statusCode, res) => {
  const token = user.getJWTToken();
  //cookie parsor is used to save the token which is generated by the jwt token because if the jwt token will be  save in the local storagae it will easily hacked so that we use the cookie parsor  for save the token//
  const option = {
    // An options object named option is created to configure the cookie. It sets the expiration time of the cookie (expires) based on the COOKIE_EXPIRES environment variable
    expires: new Date(
      Date.now() + process.env.COOKIE_EXPIRES * 24 * 60 * 60 * 1000
    ),

    //  httpOnly is set to true to make the cookie accessible only through HTTP requests.//
    httpOnly: true,
  };
  res.status(statusCode).cookie("token", token, option).json({
    success: true,
    token,
    user,
  });
};
module.exports = sendToken;
